spring:
  datasource:
    url: jdbc:mysql://localhost:3306/judgement_registry
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

judgement-registry-parser:
  webClient:
    basePath: http://reyestr.court.gov.ua/